# Pandas - Style
판다스 스타일을 적용하는 방법을 알아보겠습니다.

In [1]:
import pandas as pd

url="https://raw.githubusercontent.com/developer-sdk/kaggle-python-beginner/master/datas/kaggle-titanic/train.csv"
train=pd.read_csv(url)

# 최대값 하이라이팅

In [2]:
train.head(3).style.highlight_max(color='lightgreen')

# 최소값 하이라이팅

In [3]:
train.head(3).style.highlight_min(color='#cd4f39')

# Null값 하이라이팅

In [4]:
train.head(3).style.highlight_null(null_color='red')

# 값 그라데이션

In [5]:
train.head(3).style.background_gradient(cmap='Blues')

In [6]:
train.head(3).style.background_gradient(cmap='summer_r')

# 출력 포맷

In [7]:
train.head(3).style.format({"Fare": "${:20,.0f}"})

# 바 그래프 서식